//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokOtomasyonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeritabanıEntitiesContainer : DbContext
    {
        public VeritabanıEntitiesContainer()
            : base("name=VeritabanıEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLURUNLER> TBLURUNLERSet { get; set; }
        public virtual DbSet<TBLMUSTERILER> TBLMUSTERILERSet { get; set; }
        public virtual DbSet<TBLKATEGORILER> TBLKATEGORILERSet { get; set; }
        public virtual DbSet<TBLSATISLAR> TBLSATISLARSet { get; set; }
    }
}
